name: Build and Push Docker image

on:
  push:
      branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2

      - name: Login to GHC up
        run: echo "${{ secrets.TEST_TOKEN }}" | docker login ghcr.io -u altinshabani1 --password-stdin

      - name: Build docker image t
        run: |
          docker build . -t ghcr.io/altinshabani1/actions-runner-controller-ghcr:latest              
          docker push ghcr.io/altinshabani1/actions-runner-controller-ghcr:latest

      - name: Send Email - Copy App Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Step - Copy App Success"
          to: "altinshabani276@gmail.com"
          from: "altinshabani276@gmail.com"
          body: "Step: test.."


        
        
  
