name: Build and Push Docker image

on:
  push:
      branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2

      - name: Login to GHC
        run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u altinshabani1 --password-stdin
        
  
