name: Build and Push Docker image

on:
  push:
      branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2

      - name: Login to GHC up
        run: echo "${{ secrets.TEST_TOKEN }}" | docker login ghcr.io -u altinshabani1 --password-stdin

      - name: Build docker image t
        run: |
          docker build . -t ghcr.io/altinshabani1/actions-runner-controller-ghcr:latest              
          docker push ghcr.io/altinshabani1/actions-runner-controller-ghcr:latest



        
        
  
